package com.example.linguaquiz;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class EnglishData {
    public static List<StaticCourse> getCourses() {
        List<StaticCourse> list = new ArrayList<>();

        // --- BEGINNER ---
        list.add(new StaticCourse("en_beg_1", Language.ENGLISH, Level.BEGINNER, 1, "Greetings", "Learn basic greetings.", "Formal: Hello. Informal: Hi.", 
            Arrays.asList(new VocabularyItem("Hello", "Bonjour"), new VocabularyItem("Goodbye", "Au revoir")), 
            Arrays.asList("Hello, how are you?", "Nice to meet you."), getGreetingsQuiz()));

        list.add(new StaticCourse("en_beg_2", Language.ENGLISH, Level.BEGINNER, 2, "Numbers", "Count from 1 to 100.", "1-one, 2-two, 10-ten, 20-twenty.", 
            Arrays.asList(new VocabularyItem("First", "Premier"), new VocabularyItem("Hundred", "Cent")), 
            Arrays.asList("It's ten o'clock.", "I have twenty dollars."), getNumbersQuiz()));

        list.add(new StaticCourse("en_beg_3", Language.ENGLISH, Level.BEGINNER, 3, "Daily Routines", "Simple Present tense.", "I wake up at 7. She eats breakfast.", 
            Arrays.asList(new VocabularyItem("Always", "Toujours"), new VocabularyItem("Never", "Jamais")), 
            Arrays.asList("I usually wake up early.", "She never skips breakfast."), getRoutinesQuiz()));

        list.add(new StaticCourse("en_beg_4", Language.ENGLISH, Level.BEGINNER, 4, "Shopping", "Asking for prices.", "How much is it? Discount, receipt.", 
            Arrays.asList(new VocabularyItem("Price", "Prix"), new VocabularyItem("Sale", "Soldes")), 
            Arrays.asList("How much is this?", "I'll take it!"), getShoppingQuiz()));

        // --- INTERMEDIATE ---
        list.add(new StaticCourse("en_int_1", Language.ENGLISH, Level.INTERMEDIATE, 1, "Present Perfect", "Life experiences.", "Have/Has + past participle.", 
            Arrays.asList(new VocabularyItem("Ever", "Déjà"), new VocabularyItem("Since", "Depuis")), 
            Arrays.asList("I have visited London.", "She has just arrived."), getPresentPerfectQuiz()));

        list.add(new StaticCourse("en_int_2", Language.ENGLISH, Level.INTERMEDIATE, 2, "Modal Verbs", "Obligation and Ability.", "Can, Could, Must, Should.", 
            Arrays.asList(new VocabularyItem("Should", "Devrait"), new VocabularyItem("Must", "Doit")), 
            Arrays.asList("You should study.", "I can swim."), getModalsQuiz()));

        list.add(new StaticCourse("en_int_3", Language.ENGLISH, Level.INTERMEDIATE, 3, "Conditionals", "Hypothetical situations.", "If + present -> will. If + past -> would.", 
            Arrays.asList(new VocabularyItem("If", "Si"), new VocabularyItem("Unless", "À moins que")), 
            Arrays.asList("If it rains, I'll stay.", "Unless you hurry..."), getConditionalsQuiz()));

        list.add(new StaticCourse("en_int_4", Language.ENGLISH, Level.INTERMEDIATE, 4, "Passive Voice", "Shift focus to action.", "Be + past participle.", 
            Arrays.asList(new VocabularyItem("By", "Par"), new VocabularyItem("Built", "Construit")), 
            Arrays.asList("The cake was eaten.", "It was made in China."), getPassiveQuiz()));

        // --- ADVANCED ---
        list.add(new StaticCourse("en_adv_1", Language.ENGLISH, Level.ADVANCED, 1, "Inversion", "Emphasis and formal style.", "Never have I seen... Rarely does she...", 
            Arrays.asList(new VocabularyItem("Rarely", "Rarement"), new VocabularyItem("Seldom", "Rarement")), 
            Arrays.asList("Never have I felt so happy.", "Seldom do we see this."), getInversionQuiz()));

        list.add(new StaticCourse("en_adv_2", Language.ENGLISH, Level.ADVANCED, 2, "Academic Writing", "Formal English.", "Demonstrate, utilize, furthermore.", 
            Arrays.asList(new VocabularyItem("Furthermore", "De plus"), new VocabularyItem("However", "Cependant")), 
            Arrays.asList("Furthermore, the results show...", "However, we disagree."), getAcademicQuiz()));

        list.add(new StaticCourse("en_adv_3", Language.ENGLISH, Level.ADVANCED, 3, "Idioms", "Sound like a native.", "Piece of cake, Bite the bullet.", 
            Arrays.asList(new VocabularyItem("Idiom", "Expression"), new VocabularyItem("Bite", "Mordre")), 
            Arrays.asList("It's a piece of cake.", "Bite the bullet."), getIdiomsQuiz()));

        return list;
    }

    private static List<QuizQuestion> getGreetingsQuiz() { return Arrays.asList(new QuizQuestion(101, "Which is formal?", Arrays.asList("Hi", "Hey", "Good morning", "Yo"), 2), new QuizQuestion(102, "Au revoir?", Arrays.asList("Hello", "Bye", "Goodbye", "Hi"), 2), new QuizQuestion(103, "How are you?", Arrays.asList("I'm fine", "Alex", "No", "Yes"), 0), new QuizQuestion(104, "Enchanté?", Arrays.asList("Hi", "Nice to meet you", "Bye", "Please"), 1), new QuizQuestion(105, "Please?", Arrays.asList("Merci", "S'il vous plaît", "Pardon", "Non"), 1), new QuizQuestion(106, "Thank you?", Arrays.asList("S'il vous plaît", "Merci", "De rien", "Bonjour"), 1), new QuizQuestion(107, "Informal?", Arrays.asList("Good morning", "What's up?", "Hello", "Greetings"), 1), new QuizQuestion(108, "Welcome?", Arrays.asList("Merci", "Bienvenue", "Bonjour", "Au revoir"), 1), new QuizQuestion(109, "I'm fine?", Arrays.asList("Je vais bien", "Je suis Alex", "Au revoir", "Merci"), 0), new QuizQuestion(110, "Sorry?", Arrays.asList("Pardon", "Merci", "Bonjour", "S'il vous plaît"), 0)); }
    private static List<QuizQuestion> getNumbersQuiz() { return Arrays.asList(new QuizQuestion(201, "3:30?", Arrays.asList("Half past three", "Three thirty", "Both correct", "None"), 2), new QuizQuestion(202, "100?", Arrays.asList("Ten", "Hundred", "Thousand", "Million"), 1), new QuizQuestion(203, "1st?", Arrays.asList("One", "First", "Once", "Oneth"), 1), new QuizQuestion(204, "40?", Arrays.asList("Fourty", "Forty", "Forte", "Four"), 1), new QuizQuestion(205, "12?", Arrays.asList("Ten", "Eleven", "Twelve", "Twenty"), 2), new QuizQuestion(206, "Midnight?", Arrays.asList("Midi", "Minuit", "Matin", "Soir"), 1), new QuizQuestion(207, "3rd?", Arrays.asList("Three", "Third", "Triple", "Threeth"), 1), new QuizQuestion(208, "20?", Arrays.asList("Two", "Twelve", "Twenty", "Ten"), 2), new QuizQuestion(209, "90?", Arrays.asList("Ninety", "Ninety-nine", "Nineteen", "Nine"), 0), new QuizQuestion(210, "1000?", Arrays.asList("Hundred", "Million", "Thousand", "Billion"), 2)); }
    private static List<QuizQuestion> getRoutinesQuiz() { return Arrays.asList(new QuizQuestion(301, "He ___ (wake) up.", Arrays.asList("wake", "wakes", "waking", "woke"), 1), new QuizQuestion(302, "I ___ (not) like tea.", Arrays.asList("don't", "doesn't", "no", "am not"), 0), new QuizQuestion(303, "100% frequency?", Arrays.asList("Often", "Always", "Never", "Rarely"), 1), new QuizQuestion(304, "She ___ dinner.", Arrays.asList("cook", "cooks", "cooking", "cooked"), 1), new QuizQuestion(305, "Do you ___ English?", Arrays.asList("speak", "speaks", "speaking", "spoke"), 0), new QuizQuestion(306, "Always?", Arrays.asList("Toujours", "Jamais", "Souvent", "Parfois"), 0), new QuizQuestion(307, "Never?", Arrays.asList("Souvent", "Jamais", "Toujours", "Parfois"), 1), new QuizQuestion(308, "Usually?", Arrays.asList("Habituellement", "Rarement", "Parfois", "Jamais"), 0), new QuizQuestion(309, "We ___ (go) home.", Arrays.asList("go", "goes", "going", "gone"), 0), new QuizQuestion(310, "They ___ (watch) TV.", Arrays.asList("watch", "watches", "watching", "watched"), 0)); }
    private static List<QuizQuestion> getShoppingQuiz() { return Arrays.asList(new QuizQuestion(401, "How much ___ it?", Arrays.asList("are", "is", "am", "be"), 1), new QuizQuestion(402, "Any vs Some?", Arrays.asList("Any for questions", "Some for questions", "Both same", "None"), 0), new QuizQuestion(403, "Receipt?", Arrays.asList("Ticket", "Vêtement", "Argent", "Magasin"), 0), new QuizQuestion(404, "Discount?", Arrays.asList("Prix", "Réduction", "Achat", "Vente"), 1), new QuizQuestion(405, "Sale?", Arrays.asList("Vendu", "Soldes", "Cher", "Gratuit"), 1), new QuizQuestion(406, "Size?", Arrays.asList("Couleur", "Taille", "Prix", "Marque"), 1), new QuizQuestion(407, "Can I try it ___?", Arrays.asList("in", "at", "on", "up"), 2), new QuizQuestion(408, "I'll ___ it (buy).", Arrays.asList("take", "give", "send", "make"), 0), new QuizQuestion(409, "Cash or ___?", Arrays.asList("Paper", "Card", "Check", "Gold"), 1), new QuizQuestion(410, "Expensive?", Arrays.asList("Cher", "Bon marché", "Gratuit", "Petit"), 0)); }
    private static List<QuizQuestion> getPresentPerfectQuiz() { return Arrays.asList(new QuizQuestion(501, "I ___ seen it.", Arrays.asList("have", "has", "am", "was"), 0), new QuizQuestion(502, "Since 2010?", Arrays.asList("for", "since", "ago", "last"), 1), new QuizQuestion(503, "For 5 years?", Arrays.asList("for", "since", "ago", "during"), 0), new QuizQuestion(504, "Have you ___?", Arrays.asList("already", "ever", "yet", "since"), 1), new QuizQuestion(505, "She hasn't finished ___.", Arrays.asList("already", "just", "yet", "ever"), 2), new QuizQuestion(506, "He ___ just arrived.", Arrays.asList("is", "has", "was", "does"), 1), new QuizQuestion(507, "Past participle of 'write'?", Arrays.asList("wrote", "written", "writing", "writes"), 1), new QuizQuestion(508, "PP focus is on:", Arrays.asList("Past time", "Result now", "Future", "Duration only"), 1), new QuizQuestion(509, "We ___ (be) friends for long.", Arrays.asList("are", "were", "have been", "was"), 2), new QuizQuestion(510, "Question form:", Arrays.asList("You have?", "Have you?", "Did you?", "Do you have?"), 1) ); }
    private static List<QuizQuestion> getModalsQuiz() { return Arrays.asList(new QuizQuestion(601, "Advice?", Arrays.asList("Must", "Can", "Should", "Might"), 2), new QuizQuestion(602, "Strong obligation?", Arrays.asList("Can", "May", "Must", "Should"), 2), new QuizQuestion(603, "Ability?", Arrays.asList("Can", "Must", "Should", "Shall"), 0), new QuizQuestion(604, "Might?", Arrays.asList("Possibilité", "Obligation", "Certitude", "Interdiction"), 0), new QuizQuestion(605, "Mustn't?", Arrays.asList("Interdiction", "Permission", "Possibilité", "Conseil"), 0), new QuizQuestion(606, "May I?", Arrays.asList("Permission", "Obligation", "Ordre", "Doute"), 0), new QuizQuestion(607, "Shouldn't?", Arrays.asList("Conseil négatif", "Interdiction", "Doute", "Futur"), 0), new QuizQuestion(608, "Can vs Could?", Arrays.asList("Could is past", "Can is past", "Same", "None"), 0), new QuizQuestion(609, "Don't have to?", Arrays.asList("Pas obligé", "Interdit", "Obligé", "Doute"), 0), new QuizQuestion(610, "Correct:", Arrays.asList("He can swim", "He can swims", "He can to swim", "He can swimming"), 0)); }
    private static List<QuizQuestion> getConditionalsQuiz() { return Arrays.asList(new QuizQuestion(701, "If I ___ rich.", Arrays.asList("am", "was", "were", "be"), 2), new QuizQuestion(702, "Unless?", Arrays.asList("Si", "À moins que", "Car", "Puisque"), 1), new QuizQuestion(703, "If + Present -> ?", Arrays.asList("Will", "Would", "Was", "Been"), 0), new QuizQuestion(704, "If + Past -> ?", Arrays.asList("Will", "Would", "Was", "Been"), 1), new QuizQuestion(705, "Type 0?", Arrays.asList("Facts", "Dreams", "Regrets", "Future"), 0), new QuizQuestion(706, "If it rains...", Arrays.asList("I will stay", "I would stay", "I stayed", "I am stay"), 0), new QuizQuestion(707, "Were for all?", Arrays.asList("Yes in Type 2", "No", "Only for I", "Only for He"), 0), new QuizQuestion(708, "Condition?", Arrays.asList("If", "But", "And", "Or"), 0), new QuizQuestion(709, "If she studies...", Arrays.asList("she passes", "she will pass", "she would pass", "she pass"), 1), new QuizQuestion(710, "Real situation?", Arrays.asList("Type 1", "Type 2", "Type 3", "None"), 0)); }
    private static List<QuizQuestion> getPassiveQuiz() { return Arrays.asList(new QuizQuestion(801, "Form: be + ___", Arrays.asList("past participle", "infinitive", "present", "gerund"), 0), new QuizQuestion(802, "By introduces:", Arrays.asList("Agent", "Time", "Place", "Reason"), 0), new QuizQuestion(803, "Was built?", Arrays.asList("Past passive", "Present passive", "Future", "None"), 0), new QuizQuestion(804, "Is made?", Arrays.asList("Present passive", "Past passive", "Future", "None"), 0), new QuizQuestion(805, "Made ___ China.", Arrays.asList("in", "at", "on", "by"), 0), new QuizQuestion(806, "Letter ___ sent.", Arrays.asList("was", "is", "has", "will"), 0), new QuizQuestion(807, "Active focus?", Arrays.asList("Subject", "Action", "Object", "None"), 0), new QuizQuestion(808, "Passive focus?", Arrays.asList("Action/Object", "Subject", "Time", "None"), 0), new QuizQuestion(809, "Correct:", Arrays.asList("It was taken", "It was took", "It was take", "It were taken"), 0), new QuizQuestion(810, "Future passive?", Arrays.asList("Will be + part", "Will + part", "Be + part", "None"), 0)); }
    private static List<QuizQuestion> getInversionQuiz() { return Arrays.asList(new QuizQuestion(901, "Never ___ I.", Arrays.asList("have", "I have", "am", "was"), 0), new QuizQuestion(902, "Rarely?", Arrays.asList("Rarement", "Souvent", "Parfois", "Jamais"), 0), new QuizQuestion(903, "Seldom?", Arrays.asList("Souvent", "Rarement", "Parfois", "Jamais"), 1), new QuizQuestion(904, "Inversion style?", Arrays.asList("Formal", "Informal", "Slang", "Kids"), 0), new QuizQuestion(905, "Only then?", Arrays.asList("Seulement alors", "Jamais", "Toujours", "Avant"), 0), new QuizQuestion(906, "Hardly?", Arrays.asList("À peine", "Beaucoup", "Très", "Assez"), 0), new QuizQuestion(907, "Not only...?", Arrays.asList("but also", "and also", "so also", "but"), 0), new QuizQuestion(908, "Little did he...", Arrays.asList("know", "knows", "knew", "knowing"), 0), new QuizQuestion(909, "No sooner...?", Arrays.asList("than", "when", "that", "then"), 0), new QuizQuestion(910, "Correct:", Arrays.asList("Never have I", "Never I have", "Never have me", "None"), 0)); }
    private static List<QuizQuestion> getAcademicQuiz() { return Arrays.asList(new QuizQuestion(1001, "Furthermore?", Arrays.asList("De plus", "Cependant", "Car", "Donc"), 0), new QuizQuestion(1002, "However?", Arrays.asList("Cependant", "De plus", "Car", "Donc"), 0), new QuizQuestion(1003, "Utilize?", Arrays.asList("Utiliser", "Voir", "Faire", "Dire"), 0), new QuizQuestion(1004, "Demonstrate?", Arrays.asList("Démontrer", "Cacher", "Finir", "Aider"), 0), new QuizQuestion(1005, "Consequently?", Arrays.asList("Par conséquent", "Parfois", "Avant", "Après"), 0), new QuizQuestion(1006, "Moreover?", Arrays.asList("En outre", "Mais", "Puisque", "Alors"), 0), new QuizQuestion(1007, "Academic style?", Arrays.asList("Formal", "Casual", "Short", "Texting"), 0), new QuizQuestion(1008, "Nevertheless?", Arrays.asList("Néanmoins", "Donc", "Parce que", "Si"), 0), new QuizQuestion(1009, "Thus?", Arrays.asList("Ainsi", "Mais", "Car", "Or"), 0), new QuizQuestion(1010, "Ascertain?", Arrays.asList("S'assurer", "Ignorer", "Oublier", "Douter"), 0)); }
    private static List<QuizQuestion> getIdiomsQuiz() { return Arrays.asList(new QuizQuestion(1101, "Bite the bullet?", Arrays.asList("Courage", "Manger", "Dormir", "Peur"), 0), new QuizQuestion(1102, "Piece of cake?", Arrays.asList("Facile", "Difficile", "Gâteau", "Faim"), 0), new QuizQuestion(1103, "Under weather?", Arrays.asList("Malade", "Pluie", "Soleil", "Heureux"), 0), new QuizQuestion(1104, "Blue moon?", Arrays.asList("Rarement", "Souvent", "Nuit", "Espace"), 0), new QuizQuestion(1105, "Arm and leg?", Arrays.asList("Cher", "Pas cher", "Santé", "Sport"), 0), new QuizQuestion(1106, "Break a leg?", Arrays.asList("Bonne chance", "Malheur", "Hôpital", "Danse"), 0), new QuizQuestion(1107, "Hit nail?", Arrays.asList("Juste", "Faux", "Marteau", "Colère"), 0), new QuizQuestion(1108, "Ball in court?", Arrays.asList("À toi de jouer", "Sport", "Erreur", "Perdu"), 0), new QuizQuestion(1109, "Pull leg?", Arrays.asList("Blaguer", "Aider", "Tomber", "Marcher"), 0), new QuizQuestion(1110, "Cut to chase?", Arrays.asList("But", "Courir", "Finir", "Début"), 0)); }
}
